name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - test  # Update this to your branch name
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - test  # Update this to your branch name

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          cd client  # Change to your client-side folder
          npm install

      - name: Build client app
        run: |
          cd client  # Change to your client-side folder
          npm run build

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/client'  # Change to your client-side folder
          output_location: '/client/build'  # Change to your build output folder
          api_location: ''  # Set to empty since the API is hosted separately

